<?xml version="1.0" encoding="utf-8"?><Database Name="DocIT" Class="DocITDBDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="WebSettings" ConnectionString="Data Source=HOMEACER;Initial Catalog=DocIT;Integrated Security=True;" SettingsObjectName="System.Configuration.ConfigurationManager.ConnectionStrings" SettingsPropertyName="DocITConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.User_Locations" Member="User_Locations">
    <Type Name="User_Location">
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="user_id" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="location_id" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="date_modified" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
    </Type>
  </Table>
</Database>